FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o workspace-manager

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/workspace-manager .
EXPOSE 4000
ENTRYPOINT ["./workspace-manager"]
